export const routerUrls = Object.freeze({
  home: { url: '/', name: 'Home' },
  matches: { url: '/', name: 'Matches' },
  results: { url: '/', name: 'Results' },
  tables: { url: '/', name: 'Tables' },
  teams: { url: '/', name: 'Teams' },
  social: { url: '/', name: 'Social' },
  players: {url: '/', name: 'Players'},
  broadcast: {url: '/', name: 'Broadcast'},
  dashboard: {url: '/', name: 'Dashboard'},
  playerStats: {url: '/', name: 'Player Stats'},
  teamStats: {url: '/', name: 'Team Stats'},
  transfers: {url: '/', name: 'Transfers'},
  partners: {url: '/', name: 'Partners'},
  about: {url: '/', name: 'About'},
  publications: {url: '/', name: 'Publications'},
  contact: {url: '/', name: 'Contact'},
  egaTwitter: {url: '/', name: 'EGA on Twitter'},
  egaFacebook: {url: '/', name: 'EGA on Facebook'},
  egaVk: {url: '/', name: 'EGA on VK'},
  egaInstagram: {url: '/', name: 'EGA on Instagram'},
  egaDiscord: {url: '/', name: 'EGA on Discord'}
});